blog/blog/urls.py
from django.conf import settings
from django.conf.urls import include, url 
from django.conf.urls.static import static 
from django.contrib import admin 

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
url(r'^admin/', admin.site.urls),
url(r'^comments/', include("comments.urls", namespace='comments')),
url(r'^register/', register_view, name='register'), 
url(r'^login/', login_view, name='login'), 
url(r'^logout/', logout_view, name='logout'), 
url(r'^', include("posts.urls", namespace='post')),







]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/posts/urls.py
from django.conf.urls import  url

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	about_me, 
	)

urlpatterns =[
 
    url(r'^$',post_list, name='list'),
    url(r'^about_me/$',about_me, name='about_me'),

	url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w.@+-]+)/$', post_detail,  name='detail'),
    url(r'^(?P<slug>[\w.@+-]+)/edit/$', post_update, name='update'),
	url(r'^(?P<slug>[\w.@+-]+)/delete/$', post_delete),


]

blog/posts/models.py
from __future__ import unicode_literals
from django.conf import settings 
from django.core.urlresolvers import reverse 
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.contrib.contenttypes.models import ContentType


from django.utils.safestring import mark_safe
from django.utils import timezone

from markdown_deux import markdown 

from comments.models import Comment  
from .utils import get_read_time

# Create your models here.



class PostManager(models.Manager):
	def active (self, *args, **kwargs):
		return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())






def upload_location(instance, filename):
	filebase, extension = filename.split(".")
	return "%s/%s.%s" %(instance.id, instance.id, extension)





class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	title = models.CharField(max_length=120)
	slug = models.SlugField(unique=True)
	image = models.ImageField(upload_to=upload_location, null=True, blank=True,
		width_field="width_field",
	 height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	read_time = models.TimeField(null=True, blank=True)
	update = models.DateTimeField(auto_now=True, auto_now_add =False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


	objects = PostManager()
	def __unicode__(self):
		return self.title 

	def get_absolute_url(self):
		return reverse("post:detail", kwargs={"slug":self.slug}) 
		
	class Meta:
		ordering = ["-timestamp", "-update"]

	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content) 
		return mark_safe(markdown_text)

	@property 
	def comments(self):
		instance = self 
		qs = Comment.objects.filter_by_instance(instance)
		return qs 

	@property 
	def get_content_type(self):
		instance = self 
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type

def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs= Post.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug 



def pre_save_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug: 
		instance.slug = create_slug(instance)
	if instance.content:
		html_string = instance.get_markdown()
		read_time_var = get_read_time(html_string)
		instance.read_time = read_time_var

pre_save.connect(pre_save_post_receiver, sender=Post)

blog/posts/forms.py
from django import forms 
from pagedown.widgets import PagedownWidget 
from .models import Post 

class PostForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	publish = forms.DateField(widget=forms.SelectDateWidget)
	class Meta: 
		model = Post 
		fields = [
		"title",
		"content", 
		"image",
		'draft',
		'publish',

			 ]

blog/posts/views.py
from urllib import quote_plus 

from django.contrib import messages 

from django.db.models import Q 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect, Http404
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone 

# Create your views here.
from comments.models import Comment 
from .models import Post 
from .forms import PostForm 
from comments.forms import CommentForm





def post_create(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404

	
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance= form.save(commit=False)
		instance.user = request.user 
		instance.save()
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	


	context = {
	"form": form,
	#"instance": instance, 
	}

	


	return render(request, "post_form.html", context )

def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)

	if instance.publish > timezone.now().date() or instance.draft:
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404 
	share_string = quote_plus(instance.content)
 	
 	initial_data = {
 		"content_type": instance.get_content_type, 
 		"object_id": instance.id,
 	}
	 

	form = CommentForm(request.POST or None, initial= initial_data)

	if form.is_valid() and request.user.is_authenticated():
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get("object_id")
		content_data = form.cleaned_data.get("content")
		parent_obj = None 
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(parent__id=parent_id)
			if parent_qs.exists() and parent_qs.count()==1:
				parent_obj = parent_qs.first()




		new_comment, created = Comment.objects.get_or_create(
			user = request.user,
			content_type = content_type, 
			object_id = obj_id, 
			content = content_data,
			parent = parent_obj,
			)

		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())


	
	comments = instance.comments #Comment.objects.filter_by_instance(instance)

	#queryset = Post.objects.all()
	context = {
		#"object_list": queryset,
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
		"comments": comments,
		"comment_form": form,
	}

	return render(request, "post_detail.html", context)

def post_list(request):
	today = timezone.now().date()
	queryset_list= Post.objects.active()
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()

	query = request.GET.get("q")	
	if query:
		queryset_list = queryset_list.filter(
			Q(title__icontains=query)|
			Q(content__icontains=query)|
			Q(user__first_name__icontains=query)|
			Q(user__last_name__icontains=query)
			).distinct()

	paginator = Paginator(queryset_list, 5) # Show 25 contacts per page
	page_request_var ="page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	#instance = get_object_or_404(Post, id=1)

	context = {
		"object_list": queryset,
		"title": "List",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request, "post_list.html", context)





def post_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance =form.save(commit=False)
		instance.save()
		messages.success(request, "Item saved", extra_tags='html_safe')

		return HttpResponseRedirect(instance.get_absolute_url())
	else: 
		messages.error(request, "item not saved")


	context = {
	
		"title": instance.title,
		"form": form,
		"instance": instance,
	}
	return render(request, "post_form.html", context)




def post_delete(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Successfully Deleted")
	return redirect("post:list") 


def about_me(request):
	return render(request, "about_me.html", {})

blog/templates/about_me.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block content %}
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - About</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="post.html">Sample Post</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('static/img/about-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>About Me</h1>
                        <hr class="small">
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="static/js/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="static/js/clean-blog.min.js"></script>

</body>

</html>

{% endblock content %}

blog/templates/base.html
{% load staticfiles %}
<html>
<head>
 
 <title>{% block title_head %}Kazblog{% endblock title_head %}</title>
 
 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> 

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css'>
<link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
 <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>





<link rel='stylesheet' href='{% static "css/base.css" %}' />
<style>
{% block style %}{% endblock style %}
</style>

{% block head_extra %} {% endblock head_extra %}
</head>
 <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

 	<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% include "messages_display.html" %}
    <!-- Navigation -->
    <div class="container">
    <nav class="navbar navbar-default navbar-pills  
    navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <a class="navbar-brand" href='{% url "post:list"%}'>Kevinski Blog</a>
                

            </div>

           <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" >
                <ul class="nav navbar-nav navbar-right">
         
       {% block post_detail_link %}


		{% endblock post_detail_link%}
		{% if not request.user.is_authenticated%}
		<li> 
		<a href='{% url "post:about_me"%}'>About Me</a>
	</li>
		<li>
		<li> <a href='{% url "register" %}'>Register</a></li>
		</li>
		<li>  
		<li> <a href='{% url "login" %}'>Login</a></li>
		<li>
		{% else %}

		<li>
				<li> 
		<a href='{% url "post:about_me"%}'>About Me</a>
	</li>
		<li> <a href='{% url "logout" %}'>Logout</a></li>
		<li> 
		{% endif %}
		
		{% if request.user.is_superuser%}
		<li>
	 	<li><a href='{% url "post:create" %}'>Create</a></li>
	 	<li> 
		{% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
</div> 


	

		
<div class ='row'>
{% block content %}


{% endblock content %}


</div> 

<script src="http://code.jquery.com/jquery-1.12.4.min.js"
integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
crossorigin="anonymous"></script>


<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>


<script type="text/javascript">
function collapseNavbar() {
    if ($(".navbar").offset().top > 50) {
        $(".navbar-fixed-top").addClass("top-nav-collapse");
    } else {
        $(".navbar-fixed-top").removeClass("top-nav-collapse");
    }
}

$(window).scroll(collapseNavbar);
$(document).ready(collapseNavbar);

$(document).ready(function(){
	$(".content-markdown").each(function(){
	var content= $(this).text()
	var markedContent = marked(content)
	$(this).html(markedContent);
	})
	$(".post-detail-item img").each(function(){
		$(this).addClass("img-responsive");
	})

	var titleItem =$("#id_title");
	$("#preview-title").text(titleItem.val())

	var contentInput =$("#id_content");
		
	
	function setContent(value){
		var markedContent = marked(value)
		$("#preview-content").html(markedContent)
		$("#preview-content img").each(function(){
			$(this).addClass("img-responsive")
		})
	}
	setContent(contentInput.val())
	
	contentInput.keyup(function(){
		var newContent = $(this).val()
		setContent(newContent)
	})

	$(".comment-reply-btn").click(function(event){
		event.preventDefault();
		$(this).parent().next(".comment-reply").fadeToggle();

	})




	})
	

</script> 
 </body>





</html> 

blog/templates/comment_thread.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_title %}{{instance.title}} | {{ block.super }}{% endblock head_title %} 


{% block content %}
{{ comment }}
<div class="col-sm-6 col-sm-offset-3">

		

	
  		<p>{{ comment.content}}</p>
  	
  		<footer>Via {{ comment.user }} | {{ comment.timestamp|timesince }} ago| {% if comment.children.count > 0%}{{comment.children.count }}Comment {% if comment.childen.count > 1 %}s{% endif %}{% endif %} {% if request.user == comment.user %}<a href="{{ comment.get_delete_url}}">Delete</a>{% endif %}</footer>
	<blockquote>
  		<p>{{ child_comment.content}}</p>
  	
  		<footer>Via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago | {% if request.user == child_comment.user %} <a href="{{ child_comment.get_delete_url}}">Delete</a>{% endif %}</footer>
  	</blockquote> 
  	{{ endfor }}
	
		{% if request.user.is_authenticated %}

		<form method='POST' action='.'>{% csrf_token %}
			{{ form|crispy }}
			<input type='hidden' name'=parent_id' value= '{{ comment.id}}'>

			<input type='submit' value='Reply' class= 'btn btn-default'>
		</form>
		{% else %}

		<p>You Must Login to Comment </p> 
		{% endif %} 



<hr/> 
		


{% endblock content  %}

 </body>






</html> 

blog/templates/confirm_delete.html
 {% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_title %}{{instance.title}} | {{ block.super }}{% endblock head_title %} 


{% block content %}

<div class="col-sm-6 col-sm-offset-3">
	<h1>Confirm Delete </h1>


		<form method='POST' action='.'>{% csrf_token %}
			<p>Are you sure you want to delete:"{{ object.content }}"?</p>
			<input type='submit' value='Confirm' class= 'btn btn-warning'>
			<a href="{{object.get_absolute_url}}" class='btn btn-default'>Cancel</a>
		</form>



<hr/> 
		


{% endblock content  %}

 </body>






</html> 

blog/templates/form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

 

 {% block content %}
<div class='col-sm-6 col-sm-offset-3'>

<h1>{{ title }}</h1>

 <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %} 

{{ form|crispy }} 

<input type='submit' class='btn-btn-primary' value='{{ title }}'> 
</form> 
</div> 

{% endblock content %}

blog/templates/messages_display.html
{% if messages %}
<div class="alert alert-success"> 

<ul class="messages">
{% for message in messages %}
<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
{% endfor %}
</ul>

</div>
{% endif %}

blog/templates/post_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

 

{% block head_extra %} 
{{ form.media }}
{% endblock head_extra %}

 {% block content %}
<div class='col-sm-6'>
<h1>Preview</h1>
<div class='content-preview'>
	<h3 id='preview-title'></h3>
	<!--<input id='preview-title'/>--> 
	<p id='preview-content'></p>
</div>
</div>

<div class='col-sm-6'> 
<h1>Form</h1>

 <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %} 

{{ form|crispy }} 

<input type='submit' class='btn-btn-primary' value='Submit Post'> 
</form> 
</div> 

{% endblock content %}

blog/templates/post_list.html
{%extends "base.html"%}
{% block content %}

<div class='col-sm-8 col-sm-offset-2 '> 


<p class='lead'>{{ title }}</p>

<form method='GET' action='' class='row'>
  <div class='col-sm-6 '>
  <div class= 'input-group'>
    <input class='form-control' type='text'  name='q' placeholder='Search posts' value='{{request.GET.q}}'/>
    <span class='input-group-btn'>
    <!--<input class='btn btn-default' type='submit' value='search'/>-->
    <button class='btn btn-default' type='button'>Search <i class="fa fa-search" aria-hidden="true"></i>
</button>
  </span> 
  </div>
</div>
</form>

<div class="row">
{% for obj in object_list %}





  <div class="col-sm-12">
    <div class="thumbnail">
    	{% if obj.image %}
      <!--<img src="..." alt="...">-->
     
      <img src='{{ obj.image.url }}' class='img-rounded' />
      {% endif %}
   

      <div class="caption post-detail-item">
        {%if obj.draft%}<h3>Draft</h3>{% endif %}
        {% if obj.publish > today%}<h3>Future Post</h3>{% endif %}
        <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> <small>{{ obj.timestamp|timesince }} ago</small></h3>
        <P>{% if obj.user.get_full_name %}Author:{{ obj.user.get_full_name }}{% endif %}</P>
       {{ obj.get_markdown|truncatechars_html:120 }}
        <p><a href='{{ obj.get_absolute_url }}' class="btn btn-primary" role="button">Read More</a></p> 
        
    </div>
  
  </div>
</div> 


{% endfor %}
  <hr/>
<div class="pagination">
  <ul class = "pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
      
          <ul class="pager">
                    <li class="previous">
                          <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}&q={{ request.GET.q }}">Previous Posts &rarr;
                    </li>
                </ul></a>
        {% endif %}

        <span class="breadcrumb">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
                  <ul class="pager">
                    <li class="next">

            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}&q={{ request.GET.q}}">Older Posts &rarr;</a>
          </li>
        </ul></a>
        {% endif %}
    </span>
  </ul> 
</div>
</div>
</div> 




{% endblock content %}